### ISSUE TITLE
Uninsatll VM from instance produced an error

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jscockpit#157]
**Steps**
I installed the following BP which will create a VM in a deployed CS

> g8client__dubai:
  g8.url: 'du-conv-2.demo.greenitglobe.com'
  g8.login: 'gig'
  g8.password: 'KrOe6gE9K5nCQdmretfXnj'
  g8.account: 'gig'

> vdc__helloislam:
>   g8.client.name: 'dubai'                    
>                     
> node.ovc__vmislam:
>     os.image: 'ubuntu 16.04 x64'
>     disk.size: 10
>     datadisks:
>         - 'name:disk1 size:50 type:normal'
>         - 'name:disk2 size:50 type:normal'
>     os.size: 2
>     ports:
>         - '139:139'
>         - '445:445'
>         - '137:137'
>         - '138:138'
>     vdc: 'helloislam'

- Open the "vmislam" from the repo instance page
- From the drop down choose "Uninstall**

**Actual Result**
![screenshot from 2016-07-25 12-23-07](https://cloud.githubusercontent.com/assets/17981089/17098977/1584da7e-526e-11e6-8208-9b65d078dd1d.png)

**Comment by zaibon** [comment]
This is not a cockpit error. Problems comes from AYS itself I think. 
From the error I see that the uninstall action are not executed in the order they should.
The `In order to delete a cloudspace it can not contain Machines` message shows that AYS tried to delete the cloudspace before deleting the machine inside first.
So probably AYS did uninstall of the vdc service before uninstall of the node.

**Comment by islamTaha12** [comment]
When I try to "Delete" it, The following error was produced
![screenshot from 2016-07-25 12-51-43](https://cloud.githubusercontent.com/assets/17981089/17099155/31e785b2-526f-11e6-9e46-83d9b53471e0.png)

**Comment by zaibon** [comment]
should be fixed by https://github.com/Jumpscale/jumpscale_core8/commit/8bb72bf615c4bebca8ef5529ed6aad473790f45e
