### ISSUE TITLE
cockpit_portal: add API page to space navigator

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jscockpit#251]
Instead of it being in the AYS portal by default.
A default portal installation shows a page not found currently.

**Comment by abdulrahmantkhalifa** [comment]
due to that fact that the portal code, more specifically the nav.wiki page, is part if the sandboxing which means that a service cannot write to it unless it is  part of the build process , and so adjusting it in the ays service would not work; 
my suggestion to this issue is adjusting the code in the build method of cockpit in cuisine which will include both the ays build and a normal cockpit install
